In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv('C:/Users/louis/Documents/Msc data science/Essec/Big Data Analytics/FIFA_dataset.csv',delimiter=",")
line=data.shape[0]
data.dropna()
for i in range(line):
    if str(data.loc[i,'overall'])=="nan":
        data=data.drop(i)
Country={'Argentina':0,'Australia':1, 'Belgium':2,'Brazil':3,'Colombia':4,'Costa Rica':5,'Croatia':6,'Denmark':7,'Egypt':8,'England':9,'France':10,'Germany':11,'Iceland':12,'Iran':13,'Japan':14,'Korea Republic':15,'Mexico':16,'Morocco':17,'Nigeria':18,'Panama':19,'Peru':20,'Poland':21,'Portugal':22,'Russia':23,'Saudi Arabia':24,'Senegal':25,'Serbia':26,'Spain':27,'Sweden':28,'Switzerland':29,'Tunisia':30,'Uruguay':31}
data['Country']=data['Country'].map(Country)

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import cross_validation
from sklearn.model_selection import cross_val_score

X_pred=data.loc[data['Year']==2018]
X_pred2014=data.loc[data['Year']==2014]
X_train=data.loc[data['Year']!=2018]
X_train2014=data.loc[data['Year']<2014]
#print(X_train)
cols=[0,8,17]
#cols=[0,1,2,8,14,15,16,17]
y_train=X_train['Goal.Diiference']
y_train2014=X_train2014['Goal.Diiference']

X_train=X_train.drop(data.columns[cols],axis=1)
X_pred=X_pred.drop(data.columns[cols],axis=1)

X_train2014=X_train2014.drop(data.columns[cols],axis=1)
X_pred2014=X_pred2014.drop(data.columns[cols],axis=1)
#print(X_train2014)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [3]:
reg=LinearRegression().fit(X_train,y_train)
scores = cross_val_score(reg, X_train, y_train, cv=10)
pred=reg.predict(X_pred)
pred
reg2014=LinearRegression().fit(X_train2014,y_train2014)
scores2014 = cross_val_score(reg2014, X_train2014, y_train2014, cv=10)
pred2014=reg2014.predict(X_pred2014)
pred2014

array([ 7.8126894 , -1.82784847, 16.76513913,  3.02638452,  8.59134818,
        1.22985557,  9.97840961,  1.10663538,  2.55930483, 11.13691813,
       20.09657786, 14.48451274,  4.50358275,  3.65056398,  4.02047374,
       -0.46426887,  7.42050103, 16.48236248,  5.06768429,  4.33088346,
        1.78350406,  2.85290715,  6.3281882 , 12.67614338,  7.14829268,
        5.24831923, -3.29668157,  4.40909074,  2.99603072,  4.05395869,
        3.1435768 ,  1.01100231])

In [14]:
country=['Argentina','Australia', 'Belgium','Brazil','Colombia','Costa Rica','Croatia','Denmark','Egypt','England','France','Germany','Iceland','Iran','Japan','Korea Republic','Mexico','Morocco','Nigeria','Panama','Peru','Poland','Portugal','Russia','Saudi Arabia','Senegal','Serbia','Spain','Sweden','Switzerland','Tunisia','Uruguay']
final=pd.DataFrame({'country': country,'score':pred})
final.sort_values(['score'],ascending=False)#[:15]

#final2014=pd.DataFrame({'country': country,'score':pred2014})
#final2014.sort_values(['score'],ascending=False)#[:15]

           country      score
2          Belgium  16.197125
29     Switzerland   8.215939
9          England   7.353675
10          France   6.849249
20            Peru   5.522707
31         Uruguay   5.289187
27           Spain   5.199777
13            Iran   4.710799
3           Brazil   3.636103
24    Saudi Arabia   3.395023
26          Serbia   2.972774
5       Costa Rica   2.684208
22        Portugal   2.471483
7          Denmark   2.366499
0        Argentina   1.928623
21          Poland   1.810754
18         Nigeria   1.807751
16          Mexico   1.793699
17         Morocco   1.741659
6          Croatia   1.615937
30         Tunisia   1.000466
11         Germany   0.894600
23          Russia   0.727361
15  Korea Republic   0.408775
14           Japan   0.354555
4         Colombia   0.049132
8            Egypt  -0.018299
19          Panama  -0.060506
25         Senegal  -0.077842
28          Sweden  -0.240832
12         Iceland  -0.498405
1        Australia  -1.068543

In [5]:
np.sort(pred)

array([-1.06854283, -0.49840496, -0.24083173, -0.07784203, -0.0605057 ,
       -0.01829858,  0.04913167,  0.35455524,  0.40877466,  0.72736133,
        0.89460049,  1.00046586,  1.61593659,  1.74165898,  1.79369924,
        1.80775059,  1.81075411,  1.92862282,  2.36649857,  2.47148331,
        2.68420845,  2.97277384,  3.39502259,  3.63610256,  4.71079936,
        5.19977672,  5.28918705,  5.52270688,  6.84924877,  7.35367475,
        8.21593904, 16.19712452])

In [6]:
a=3*1.92-1.80-1.61+0.5
b=3*1.8-1.92-1.61+0.5
c=3*1.61-1.92-1.8+0.5
d=-0.5-1.8-1.61-1.92
print(a,b,c,d)

2.8499999999999996 2.37 1.61 -5.83

In [7]:
reg.coef_

array([-0.01557337,  0.00162392, -0.95411604,  0.99870738,  0.08011925,
       -0.0494263 ,  0.03069295, -0.19896189, -0.11321316,  0.342868  ,
       -0.13336701,  0.01447704,  0.0208816 ,  0.00420135, -0.04718636])

In [8]:
X_train.head()

,Year,Country,Goals.conceded,Goals.Scored,Touranaments.played,Friendlys.played,Matches.played,Matches.Won,Matches.draw,Matches.lost,Tournaments.won,overall,attack,midfield,defense
32,2006,0,8,14,3,3,6,4,0,2,3,83.000,83.00,82.000,82.0
33,2006,1,4,13,3,4,7,5,2,0,3,76.000,75.00,75.000,73.0
34,2006,2,5,8,3,2,5,2,2,1,1,75.000,73.00,71.000,75.0
35,2006,3,2,12,4,2,6,5,0,1,3,85.000,84.00,85.000,85.0
36,2006,4,1,3,0,2,2,1,1,0,0,77.375,78.75,76.875,75.5

In [9]:
X_train.corr()

,Year,Country,Goals.conceded,Goals.Scored,Touranaments.played,Friendlys.played,Matches.played,Matches.Won,Matches.draw,Matches.lost,Tournaments.won,overall,attack,midfield,defense
Year,1.000000,0.001950,-0.023777,0.038272,0.093246,-0.162724,-0.057432,0.007121,-0.056057,-0.096413,0.127057,-0.017674,0.054027,0.042810,0.029128
Country,0.001950,1.000000,-0.020362,-0.109056,-0.080375,-0.050033,-0.092982,-0.147055,0.043884,0.006111,-0.108045,-0.147427,-0.074330,-0.133666,-0.100371
Goals.conceded,-0.023777,-0.020362,1.000000,0.404164,0.341478,0.524088,0.628294,0.251402,0.357660,0.691080,0.074546,-0.024287,-0.048047,-0.038302,-0.028853
Goals.Scored,0.038272,-0.109056,0.404164,1.000000,0.573061,0.525303,0.789170,0.868145,0.249134,0.002386,0.620121,0.156463,0.129787,0.148240,0.172313
Touranaments.played,0.093246,-0.080375,0.341478,0.573061,1.000000,-0.036526,0.663401,0.592425,0.352604,0.112813,0.797260,0.030090,0.031661,0.025827,0.046791
Friendlys.played,-0.162724,-0.050033,0.524088,0.525303,-0.036526,1.000000,0.723533,0.529504,0.350404,0.391248,-0.051755,0.011592,-0.023787,-0.005137,0.007686
Matches.played,-0.057432,-0.092982,0.628294,0.789170,0.663401,0.723533,1.000000,0.805692,0.505931,0.370878,0.511956,0.029464,0.004059,0.013994,0.038076
Matches.Won,0.007121,-0.147055,0.251402,0.868145,0.592425,0.529504,0.805692,1.000000,0.082802,-0.029926,0.733140,0.128253,0.113870,0.120031,0.135973
Matches.draw,-0.056057,0.043884,0.357660,0.249134,0.352604,0.350404,0.505931,0.082802,1.000000,-0.003794,-0.021778,-0.085376,-0.091709,-0.098758,-0.056465
Matches.lost,-0.096413,0.006111,0.691080,0.002386,0.112813,0.391248,0.370878,-0.029926,-0.003794,1.000000,-0.128544,-0.083054,-0.111772,-0.090946,-0.108861
Tournaments.won,0.127057,-0.108045,0.074546,0.620121,0.797260,-0.051755,0.511956,0.733140,-0.021778,-0.128544,1.000000,0.107326,0.098226,0.102236,0.112936
overall,-0.017674,-0.147427,-0.024287,0.156463,0.030090,0.011592,0.029464,0.128253,-0.085376,-0.083054,0.107326,1.000000,0.851927,0.907298,0.927836
attack,0.054027,-0.074330,-0.048047,0.129787,0.031661,-0.023787,0.004059,0.113870,-0.091709,-0.111772,0.098226,0.851927,1.000000,0.815883,0.806239
midfield,0.042810,-0.133666,-0.038302,0.148240,0.025827,-0.005137,0.013994,0.120031,-0.098758,-0.090946,0.102236,0.907298,0.815883,1.000000,0.896579
defense,0.029128,-0.100371,-0.028853,0.172313,0.046791,0.007686,0.038076,0.135973,-0.056465,-0.108861,0.112936,0.927836,0.806239,0.896579,1.000000

In [10]:
np.mean(scores)

0.9504101588144651

In [11]:
reg.get_params

In [12]:
import statsmodels.api as sm
from scipy import stats

X=X_train
y=y_train

X2 = sm.add_constant(X)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

                            OLS Regression Results
==============================================================================
Dep. Variable:        Goal.Diiference   R-squared:                       0.955
Model:                            OLS   Adj. R-squared:                  0.953
Method:                 Least Squares   F-statistic:                     600.0
Date:                Sat, 01 Dec 2018   Prob (F-statistic):          5.72e-239
Time:                        17:12:39   Log-Likelihood:                -625.11
No. Observations:                 383   AIC:                             1278.
Df Residuals:                     369   BIC:                             1333.
Df Model:                          13
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  32.4608     39.329      0.825      0.410     -44.876     109.797
Year                   -0.0156      0.020     -0.797      0.426      -0.054       0.023
Country                 0.0016      0.007      0.225      0.822      -0.013       0.016
Goals.conceded         -0.9541      0.036    -26.389      0.000      -1.025      -0.883
Goals.Scored            0.9987      0.023     44.232      0.000       0.954       1.043
Touranaments.played     0.0801      0.047      1.720      0.086      -0.011       0.172
Friendlys.played       -0.0494      0.038     -1.289      0.198      -0.125       0.026
Matches.played          0.0307      0.029      1.071      0.285      -0.026       0.087
Matches.Won            -0.1990      0.072     -2.764      0.006      -0.341      -0.057
Matches.draw           -0.1132      0.049     -2.305      0.022      -0.210      -0.017
Matches.lost            0.3429      0.072      4.772      0.000       0.202       0.484
Tournaments.won        -0.1334      0.109     -1.219      0.224      -0.349       0.082
overall                 0.0145      0.045      0.321      0.749      -0.074       0.103
attack                  0.0209      0.025      0.845      0.399      -0.028       0.069
midfield                0.0042      0.035      0.120      0.905      -0.065       0.073
defense                -0.0472      0.040     -1.171      0.243      -0.126       0.032
==============================================================================
Omnibus:                      324.550   Durbin-Watson:                   1.856
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6418.191
Skew:                           3.561   Prob(JB):                         0.00
Kurtosis:                      21.747   Cond. No.                     7.69e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.64e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [3]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
estimator = SVR(kernel="linear")
selector = RFE(estimator, 7, step=1)
selector = selector.fit(X_train, y_train)
print("Num Features: %s" % (selector.n_features_))
print("Selected Features: %s" % (selector.support_))
print("Feature Ranking: %s" % (selector.ranking_))
X_train

Num Features: 7
Selected Features: [False False  True  True False False False  True False  True  True  True
 False False  True]
Feature Ranking: [9 8 1 1 6 2 7 1 3 1 1 1 5 4 1]

,Year,Country,Goals.conceded,Goals.Scored,Touranaments.played,Friendlys.played,Matches.played,Matches.Won,Matches.draw,Matches.lost,Tournaments.won,overall,attack,midfield,defense
32,2006,0,8,14,3,3,6,4,0,2,3,83.000,83.000,82.000,82.000
33,2006,1,4,13,3,4,7,5,2,0,3,76.000,75.000,75.000,73.000
34,2006,2,5,8,3,2,5,2,2,1,1,75.000,73.000,71.000,75.000
35,2006,3,2,12,4,2,6,5,0,1,3,85.000,84.000,85.000,85.000
36,2006,4,1,3,0,2,2,1,1,0,0,77.375,78.750,76.875,75.500
37,2006,5,2,2,1,1,2,1,0,1,0,72.000,66.000,70.000,71.000
38,2006,6,5,13,3,2,5,2,2,1,2,79.000,79.000,84.000,77.000
39,2006,7,3,7,1,3,4,2,2,0,0,78.000,77.000,78.000,75.000
40,2006,8,8,20,7,4,11,7,2,2,5,69.875,69.000,69.125,67.750
41,2006,9,2,24,6,4,10,8,2,0,4,85.000,83.000,84.000,85.000
42,2006,10,5,17,4,5,9,6,2,1,2,85.000,88.000,81.000,83.000
43,2006,11,9,36,8,6,14,11,2,1,6,84.000,83.000,81.000,82.000
44,2006,12,6,1,2,2,4,0,1,3,0,73.000,76.000,74.500,71.500
45,2006,13,6,19,4,4,8,6,2,0,2,69.000,75.000,70.000,70.000
46,2006,14,8,19,7,5,12,7,2,3,3,73.000,76.000,75.000,73.000
47,2006,15,7,19,5,4,9,5,3,1,3,72.000,72.000,74.000,71.000
48,2006,16,5,11,2,6,8,6,1,1,1,78.000,78.000,76.000,78.000
49,2006,17,4,13,1,6,7,4,1,2,0,74.000,74.000,77.000,75.000
50,2006,18,3,8,6,0,6,4,1,1,4,74.000,75.000,76.000,73.000
51,2006,19,2,2,0,2,2,1,0,1,0,67.000,68.000,67.000,68.000
52,2006,20,3,0,1,1,2,0,0,2,0,71.500,73.625,70.500,69.125
53,2006,21,11,9,4,4,8,2,1,5,1,74.000,74.000,71.000,68.000
54,2006,22,3,15,6,1,7,6,0,1,5,81.000,78.000,81.000,91.000
55,2006,23,2,4,3,2,5,2,2,1,1,78.000,79.000,76.000,77.000
56,2006,24,21,26,5,13,18,7,5,6,3,71.000,70.000,70.000,70.000
57,2006,25,2,4,2,2,4,2,1,1,1,74.000,74.000,74.000,74.000
58,2006,26,3,7,4,2,6,3,2,1,3,77.000,77.000,79.000,77.000
59,2006,27,9,21,4,6,10,7,1,2,3,85.000,85.000,84.000,81.000
60,2006,28,4,9,4,2,6,3,3,0,3,76.000,77.000,75.000,73.000
61,2006,29,5,12,2,6,8,4,3,1,1,76.000,79.000,76.000,72.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,2017,2,5,20,3,3,6,4,2,0,2,84.000,85.000,83.000,84.000
386,2017,3,0,9,3,1,4,4,0,0,3,84.000,87.000,82.000,85.000
387,2017,4,3,3,3,0,3,1,1,1,1,78.000,79.000,79.000,76.000
388,2017,5,4,9,7,0,7,3,4,0,3,72.000,66.000,70.000,71.000
389,2017,6,2,7,4,0,4,3,1,0,3,79.000,79.000,84.000,77.000
390,2017,7,2,6,3,1,4,1,3,0,1,78.000,76.000,79.000,76.000
391,2017,8,3,13,6,4,10,9,0,1,5,72.000,76.000,71.000,69.000
392,2017,9,1,5,3,2,5,3,2,0,3,81.000,82.000,81.000,81.000
393,2017,10,5,16,3,4,7,5,1,1,2,83.000,82.000,83.000,81.000
394,2017,11,6,29,6,2,8,6,2,0,5,85.000,82.000,86.000,84.000
395,2017,12,3,6,3,2,5,3,0,2,3,71.000,77.000,71.000,69.000
396,2017,13,4,10,3,4,7,5,1,1,2,69.000,75.000,70.000,70.000
397,2017,14,13,17,5,4,9,5,2,2,4,73.000,76.000,75.000,73.000
398,2017,15,7,7,3,3,6,2,3,1,1,72.000,72.000,74.000,71.000
399,2017,16,9,23,10,4,14,10,2,2,7,78.000,79.000,78.000,74.000
400,2017,17,4,17,4,4,8,6,0,2,4,74.000,74.000,77.000,75.000
401,2017,18,3,9,3,2,5,3,1,1,2,74.000,75.000,76.000,73.000
402,2017,19,5,14,7,0,7,5,2,0,5,67.000,68.000,67.000,68.000
403,2017,20,3,8,4,1,5,4,1,0,3,70.000,72.000,70.000,68.000
404,2017,21,4,10,3,2,5,3,1,1,3,79.000,82.000,77.000,77.000
405,2017,22,8,24,6,4,10,6,3,1,4,83.000,85.000,82.000,81.000
406,2017,23,16,15,3,7,10,2,4,4,1,76.000,66.000,75.000,75.000
407,2017,24,7,7,2,3,5,3,0,2,2,71.000,70.000,70.000,70.000
408,2017,25,3,11,6,2,8,4,4,0,3,74.000,74.000,74.000,74.000
409,2017,26,1,5,3,0,3,2,1,0,2,77.000,77.000,79.000,77.000
410,2017,27,3,17,3,2,5,4,1,0,3,85.000,84.000,85.000,85.000
411,2017,28,1,15,4,0,4,4,0,0,4,76.000,76.000,76.000,76.000
412,2017,29,2,10,4,1,5,4,1,0,3,78.000,77.000,75.000,75.000
413,2017,30,4,4,3,2,5,2,1,2,1,71.000,70.000,72.000,71.000
414,2017,31,6,5,3,0,3,1,1,1,1,79.000,85.000,76.000,80.000